/**
 * Groups svg shapes by color, preparing the svg file for plotting.
 * Labels each group as Inkscape layer, and numbers them: NextDraw requires that layer name starts with a number.
 * To use, open an svg in browser and run the function. Save the resulting svg by copying (e.g. "Copy element") and pasting to a text editor.
 * Remember to remove the background rect, which is generated by p5 svg plugin, or the rectangle will be plotted.
 */
function groupByColor() {
    const paths = document.querySelectorAll('path');
    const groups = new Map();
    const colors = new Set();
    paths.forEach((path) => {
        let color = path.getAttribute('stroke');
        color = color === 'none' ? path.getAttribute('fill') : color;
        let opacity = path.getAttribute('stroke-opacity');
        opacity = opacity ? opacity : (path.getAttribute('fill-opacity') ?? 1);
        colors.add(color + '-' + opacity);
    });
    Array.from(colors).forEach((color, index) => {
        const group = document.createElementNS('http://www.w3.org/2000/svg', 'g');
        document.documentElement.appendChild(group);
        groups.set(color, group);

        group.setAttribute('inkscape:groupmode', 'layer');
        group.setAttribute('id', `layer${index + 1}`);
        group.setAttribute('inkscape:label', `${index + 1} ${color}`);
        group.setAttribute('style', `display:inline`);
    });
    paths.forEach((path) => {
        let color = path.getAttribute('stroke');
        color = color === 'none' ? path.getAttribute('fill') : color;
        let opacity = path.getAttribute('stroke-opacity');
        opacity = opacity ? opacity : (path.getAttribute('fill-opacity') ?? 1);
        const group = groups.get(color + '-' + opacity);
        path.parentElement.removeChild(path);
        group.appendChild(path);
    });
    document.documentElement.setAttribute('xmlns:inkscape', 'http://www.inkscape.org/namespaces/inkscape');
    document.documentElement.setAttribute('inkscape:version', '1.3.2 (091e20e, 2023-11-25)');
}

/**
 * Extracts the "d" attribute from a path element string or returns the string as-is if it's already a d attribute.
 */
export function extractPathD(input) {
    const trimmed = input.trim();
    if (trimmed.startsWith('<')) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(trimmed, 'image/svg+xml');
        const path = doc.querySelector('path');
        if (!path) throw new Error('No <path> element found');
        return path.getAttribute('d');
    }
    return trimmed;
}

/**
 * Converts svg bezier to bezier segments. Accepts either a <path> element string or just the "d" attribute.
 * Supports both absolute (M, C, L) and relative (m, c, l) commands.
 */
export function svgPathToBezier(input) {
    const d = extractPathD(input);
    // Split path into commands and their parameters
    const commands = d.match(/[MmLlCc][^MmLlCc]*/g);
    if (!commands || commands.length === 0) {
        throw new Error('Invalid path data: no valid commands found');
    }

    const bezierSegments = [];
    let currentX = 0;
    let currentY = 0;

    for (const command of commands) {
        const type = command[0];
        const params = command
            .slice(1)
            .trim()
            .match(/-?\d+\.?\d*/g);
        if (!params) continue;

        const numbers = params.map(Number);

        if (type === 'M' || type === 'm') {
            // Move command - first pair is the move, subsequent pairs are implicit line commands
            if (type === 'M') {
                currentX = numbers[0];
                currentY = numbers[1];
            } else {
                currentX += numbers[0];
                currentY += numbers[1];
            }

            // Handle implicit line commands after move
            for (let i = 2; i < numbers.length; i += 2) {
                if (i + 1 >= numbers.length) break;

                let endx, endy;
                if (type === 'M') {
                    endx = numbers[i];
                    endy = numbers[i + 1];
                } else {
                    endx = currentX + numbers[i];
                    endy = currentY + numbers[i + 1];
                }

                // Create a linear bezier (control points lie on the line)
                const segment = {
                    x1: currentX,
                    y1: currentY,
                    x2: currentX + (endx - currentX) * 0.33,
                    y2: currentY + (endy - currentY) * 0.33,
                    x3: currentX + (endx - currentX) * 0.67,
                    y3: currentY + (endy - currentY) * 0.67,
                    x4: endx,
                    y4: endy,
                };

                bezierSegments.push(segment);
                currentX = endx;
                currentY = endy;
            }
        } else if (type === 'C' || type === 'c') {
            // Cubic bezier curve
            for (let i = 0; i < numbers.length; i += 6) {
                if (i + 5 >= numbers.length) break;

                let cp1x, cp1y, cp2x, cp2y, endx, endy;

                if (type === 'C') {
                    // Absolute coordinates
                    cp1x = numbers[i];
                    cp1y = numbers[i + 1];
                    cp2x = numbers[i + 2];
                    cp2y = numbers[i + 3];
                    endx = numbers[i + 4];
                    endy = numbers[i + 5];
                } else {
                    // Relative coordinates
                    cp1x = currentX + numbers[i];
                    cp1y = currentY + numbers[i + 1];
                    cp2x = currentX + numbers[i + 2];
                    cp2y = currentY + numbers[i + 3];
                    endx = currentX + numbers[i + 4];
                    endy = currentY + numbers[i + 5];
                }

                const segment = {
                    x1: currentX,
                    y1: currentY,
                    x2: cp1x,
                    y2: cp1y,
                    x3: cp2x,
                    y3: cp2y,
                    x4: endx,
                    y4: endy,
                };

                bezierSegments.push(segment);
                currentX = endx;
                currentY = endy;
            }
        } else if (type === 'L' || type === 'l') {
            // Line command - convert to bezier with control points on the line
            for (let i = 0; i < numbers.length; i += 2) {
                if (i + 1 >= numbers.length) break;

                let endx, endy;
                if (type === 'L') {
                    endx = numbers[i];
                    endy = numbers[i + 1];
                } else {
                    endx = currentX + numbers[i];
                    endy = currentY + numbers[i + 1];
                }

                // Create a linear bezier (control points lie on the line)
                const segment = {
                    x1: currentX,
                    y1: currentY,
                    x2: currentX + (endx - currentX) * 0.33,
                    y2: currentY + (endy - currentY) * 0.33,
                    x3: currentX + (endx - currentX) * 0.67,
                    y3: currentY + (endy - currentY) * 0.67,
                    x4: endx,
                    y4: endy,
                };

                bezierSegments.push(segment);
                currentX = endx;
                currentY = endy;
            }
        }
    }

    return bezierSegments.map(({ x1, y1, x2, y2, x3, y3, x4, y4 }) => {
        return [
            { x: x1, y: y1 },
            { x: x2, y: y2 },
            { x: x3, y: y3 },
            { x: x4, y: y4 },
        ];
    });
}

/**
 * Converts an entire SVG (as string) to an array of bezier path arrays.
 * Each path in the SVG becomes an array of bezier segments.
 */
export function svgToBezierPaths(svgString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, 'image/svg+xml');
    const paths = doc.querySelectorAll('path');

    return Array.from(paths).map((path) => svgPathToBezier(path.getAttribute('d')));
}

/**
 * Extracts fill color from a path element's style or fill attribute.
 * Returns null if no fill or fill is 'none'.
 */
function extractFill(pathElement) {
    const style = pathElement.getAttribute('style') || '';
    const fillMatch = style.match(/fill:\s*([^;]+)/);
    if (fillMatch) {
        const fill = fillMatch[1].trim();
        return fill === 'none' ? null : fill;
    }
    const fillAttr = pathElement.getAttribute('fill');
    if (fillAttr && fillAttr !== 'none') {
        return fillAttr;
    }
    return null;
}

/**
 * Converts an entire SVG to an array of path objects with segments and fill info.
 * Each path becomes: { segments: [...], fill: '#color' | null }
 */
export function svgToBezierPathsWithStyle(svgString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, 'image/svg+xml');
    const paths = doc.querySelectorAll('path');

    return Array.from(paths).map((path) => ({
        segments: svgPathToBezier(path.getAttribute('d')),
        fill: extractFill(path),
    }));
}

/**
 * Samples points along an SVG path. Returns array of {x, y} points.
 * @param {string} input - Either a <path> element string or just the "d" attribute
 * @param {number} numPoints - Number of points to sample (default 50)
 */
export function svgPathToVertices(input, numPoints = 50) {
    const d = extractPathD(input);
    const path = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    path.setAttribute('d', d);

    const length = path.getTotalLength();
    const points = [];
    for (let i = 0; i <= numPoints; i++) {
        const pt = path.getPointAtLength((i / numPoints) * length);
        points.push({ x: pt.x, y: pt.y });
    }
    return points;
}

/**
 * Converts an entire SVG to arrays of vertex points.
 * @param {string} svgString - The SVG content as a string
 * @param {number} numPoints - Points per path (default 50)
 */
export function svgToVertices(svgString, numPoints = 50) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, 'image/svg+xml');
    const paths = doc.querySelectorAll('path');

    return Array.from(paths).map((path) => svgPathToVertices(path.getAttribute('d'), numPoints));
}
